name = "monogame-webb-uppg3-test"
pages_build_output_dir = "./dist"
compatibility_date = "2025-02-05"

[[d1_databases]]
binding = "DB"
database_name = "webb-proj3-db"
database_id = "8527bdf2-83b4-423a-9f93-f025ab8ef523"
